-- Here you are going to configure all your blacklisted explosions, if you DON'T know what are you doing, leave it default and follow the tutorial
-- If you already know what im talking about have fun.

ChocoHaxBExplosion = {}

ChocoHaxBExplosion.ExplosionsList = {
    [0] = { name = "Grenade", log = true, ban = true },
    [1] = { name = "GrenadeLauncher", log = true, ban = true },
    [3] = { name = "Molotov", log = true, ban = true },
    [4] = { name = "Rocket", log = true, ban = true },
    [5] = { name = "TankShell", log = true, ban = true},
    [6] = { name = "Hi_Octane", log = false, ban = false },
    [7] = { name = "Car", log = false, ban = false },
    [8] = { name = "Plance", log = false, ban = false },
    [9] = { name = "PetrolPump", log = false, ban = false },
    [10] = { name = "Bike", log = false, ban = false },
    [11] = { name = "Dir_Steam", log = false, ban = false },
    [12] = { name = "Dir_Flame", log = false, ban = false },
    [13] = { name = "Dir_Water_Hydrant", log = false, ban = false },
    [14] = { name = "Dir_Gas_Canister", log = false, ban = false },
    [15] = { name = "Boat", log = false, ban = false },
    [16] = { name = "Ship_Destroy", log = false, ban = false },
    [17] = { name = "Truck", log = false, ban = false },
    [18] = { name = "Bullet", log = true, ban = true },
    [19] = { name = "SmokeGrenadeLauncher", log = true, ban = true },
    [20] = { name = "SmokeGrenade", log = false, ban = false },
    [21] = { name = "BZGAS", log = false, ban = false },
    [22] = { name = "Flare", log = false, ban = false },
    [23] = { name = "Gas_Canister", log = false, ban = false },
    [24] = { name = "Extinguisher", log = false, ban = false },
    [25] = { name = "Programmablear", ban = false },
    [26] = { name = "Train", log = false, ban = false },
    [27] = { name = "Barrel", log = false, ban = false },
    [28] = { name = "PROPANE", log = false, ban = false },
    [29] = { name = "Blimp", log = false, ban = false },
    [30] = { name = "Dir_Flame_Explode", log = false, ban = false },
    [31] = { name = "Tanker", log = false, ban = false },
    [32] = { name = "PlaneRocket", log = true, ban = true },
    [33] = { name = "VehicleBullet", ban = false },
    [34] = { name = "Gas_Tank", log = false, ban = false },
    [35] = { name = "FireWork", log = false, ban = false },
    [36] = { name = "SnowBall", log = false, ban = false },
    [37] = { name = "ProxMine", log = true, ban = true },
    [38] = { name = "Valkyrie_Cannon", log = true, ban = true }
}