VCAC_E = {}

VCAC_E.AntiNukeBlacklistedObjects = { -- Entities
	{name = "p_crahsed_heli_s",     ban = true , log = true},
	{name = "prop_rock_4_big2",     ban = true , log = true},
	{name = "prop_beachflag_le",    ban = true , log = true},
	{name = "prop_fnclink_05crnr1", ban = true , log = true},
	{name = "xm_prop_x17_sub",      ban = true , log = true},
	{name = "xs_prop_hamburgher_wl",ban = true , log = true},
	{name = "xs_prop_plastic_bottle_wl", ban = true , log = true},
	{name = "prop_windmill_01",     ban = true , log = true},
	{name = "prop_windmill_01_I1",  ban = true , log = true},
	{name = "prop_windmill_01_slod",ban = true , log = true},
	{name = "prop_windmill_01_slod2",ban = true , log = true},
	{name = "p_spinning_anus_s",    ban = true , log = true},
	{name = "stt_prop_ramp_adj_flip_m",ban = true , log = true},
	{name = "stt_prop_ramp_adj_flip_mb",ban = true , log = true},
	{name = "stt_prop_ramp_adj_flip_s",ban = true , log = true},
	{name = "stt_prop_ramp_adj_flip_sb",ban = true , log = true},
	{name = "stt_prop_ramp_adj_hloop",ban = true , log = true},
	{name = "stt_prop_ramp_adj_loop",ban = true , log = true},
	{name = "stt_prop_ramp_jump_l",ban = true , log = true},
	{name = "stt_prop_ramp_jump_m",ban = true , log = true},
	{name = "stt_prop_ramp_jump_s",ban = true , log = true},
	{name = "stt_prop_ramp_jump_xl",ban = true , log = true},
	{name = "stt_prop_ramp_jump_xs",ban = true , log = true},
	{name = "stt_prop_ramp_jump_xxl",ban = true , log = true},
	{name = "stt_prop_ramp_multi_loop_rb",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_l",ban = true , log = true},
	{name = "stt_prop_stunt_soccer_ball",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_l_l",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_l_m",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_l_s",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_l_xxl",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_m",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_s",ban = true , log = true},
	{name = "stt_prop_ramp_spiral_xxl",ban = true , log = true},
	{name = "prop_container_01a",ban = true , log = true},
	{name = "stt_prop_stunt_domino",ban = true , log = true},
	{name = "stt_prop_stunt_jump15",ban = true , log = true},
	{name = "stt_prop_stunt_jump30",ban = true , log = true},
	{name = "stt_prop_stunt_jump45",ban = true , log = true},
	{name = "stt_prop_stunt_jump_l",ban = true , log = true},
	{name = "stt_prop_stunt_jump_lb",ban = true , log = true},
	{name = "stt_prop_stunt_jump_loop",ban = true , log = true},
	{name = "stt_prop_stunt_jump_m",ban = true , log = true},
	{name = "stt_prop_stunt_jump_mb",ban = true , log = true},
	{name = "stt_prop_stunt_jump_s",ban = true , log = true},
	{name = "stt_prop_stunt_jump_sb",ban = true , log = true},
	{name = "stt_prop_stunt_landing_zone_01",ban = true , log = true},
	{name = "stt_prop_stunt_ramp",ban = true , log = true},
	{name = "stt_prop_stunt_soccer_goal",ban = true , log = true},
	{name = "stt_prop_stunt_soccer_lball",ban = true , log = true},
	{name = "stt_prop_stunt_soccer_sball",ban = true , log = true},
	{name = "stt_prop_stunt_target",ban = true , log = true},
	{name = "stt_prop_stunt_small",ban = true , log = true},
	{name = "stt_prop_stunt_track_start",ban = true , log = true},
	{name = "stt_prop_stunt_track_slope45",ban = true , log = true},
	{name = "stt_prop_stunt_track_slope30",ban = true , log = true},
	{name = "stt_prop_stunt_track_slope15",ban = true , log = true},
	{name = "stt_prop_stunt_track_short",ban = true , log = true},
	{name = "stt_prop_stunt_track_dwuturn",ban = true , log = true},
	{name = "stt_prop_stunt_track_dwslope45",ban = true , log = true},
	{name = "stt_prop_stunt_track_funlng",ban = true , log = true},
	{name = "stt_prop_stunt_bowling_ball",ban = true , log = true},
	{name = "stt_prop_stunt_bowling_pin",ban = true , log = true},

}

VCAC_E.AntiNukeBlacklistedVehicles = { -- Models/Vehicles/Airplanes etc etc.
	{name = "cargoplane", ban = true , log = true},
	{name = "cerberus",   ban = true , log = true},
	{name = "cerberus2",  ban = true , log = true},
	{name = "cerberus3",  ban = true , log = true},
	{name = "hauler2",    ban = true , log = true},
	{name = "phantom2",   ban = true , log = true},
	{name = "terbyte",    ban = true , log = true},
	{name = "issi4",      ban = true , log = true},
	{name = "issi5",      ban = true , log = true},
	{name = "issi6",      ban = true , log = true},
	{name = "akula",      ban = true , log = true},
	{name = "annihilator",ban = true , log = true},
	{name = "buzzard",    ban = false ,log = false},
	{name = "hunter",     ban = true , log = true},
	{name = "savage",     ban = true , log = true},
	{name = "apc",        ban = true , log = true},
	{name = "barrage",    ban = true , log = true},
	{name = "chernobog",  ban = true , log = true},
	{name = "halftrack",  ban = true , log = true},
	{name = "khanjali",   ban = true , log = true},
	{name = "minitank",   ban = true , log = true},
	{name = "rhino",      ban = false ,log = false},
	{name = "scarab",     ban = true , log = true},
	{name = "scarab2",    ban = true , log = true},
	{name = "scarab3",    ban = true , log = true},
	{name = "thruster",   ban = true , log = true},
	{name = "trailersmall2",ban = true , log = true},
	{name = "oppressor",  ban = true , log = true},
	{name = "oppressor2", ban = true , log = true},
	{name = "dominator4", ban = true , log = true},
	{name = "dominator5", ban = true , log = true},
	{name = "dominator6", ban = true , log = true},
	{name = "dukes2",     ban = true , log = true},
	{name = "impaler2",   ban = true , log = true},
	{name = "impaler3",   ban = true , log = true},
	{name = "impaler4",   ban = true , log = true},
	{name = "imperator",  ban = true , log = true},
	{name = "imperator2", ban = true , log = true},
	{name = "imperator3", ban = true , log = true},
	{name = "bruiser",    ban = true , log = true},
	{name = "bruiser2",   ban = true , log = true},
	{name = "bruiser3",   ban = true , log = true},
	{name = "brutus",     ban = true , log = true},
	{name = "brutus2",    ban = true , log = true},
	{name = "brutus3",    ban = true , log = true},
	{name = "caracara",   ban = true , log = true},
	{name = "dune4",      ban = true , log = true},
	{name = "dune5",      ban = true , log = true},
	{name = "insurgent",  ban = true , log = true},
	{name = "insurgent3", ban = true , log = true},
	{name = "menacer",    ban = true , log = true},
	{name = "nightshark", ban = true , log = true},
	{name = "technical",  ban = true , log = true},
	{name = "technical2", ban = true , log = true},
	{name = "technical3", ban = true , log = true},
	{name = "zhaba",      ban = true , log = true},
	{name = "avenger",    ban = true , log = true},
	{name = "avenger2",   ban = true , log = true},
	{name = "besra",      ban = false , log = false},
	{name = "blimp",      ban = false , log = false},
	{name = "blimp2",     ban = false , log = false},
	{name = "blimp3",     ban = false , log = false},
	{name = "jet",        ban = false , log = true},
	{name = "hydra",      ban = false , log = false},
	{name = "strikeforce",ban = true  , log = true},
	{name = "titan",      ban = false , log = false},
	{name = "volatol",    ban = true ,  log = true},
	{name = "limo2",      ban = true ,  log = true},
	{name = "zr380",      ban = true ,  log = true},
	{name = "zr3802",     ban = true ,  log = true},
	{name = "zr3803",     ban = true ,  log = true},
	{name = "deluxo",     ban = true ,  log = true},
	{name = "vigilante",  ban = true ,  log = true},
	{name = "boxville5",  ban = true ,  log = true},
	{name = "kuruma2",    ban = true ,  log = true},
	{name = "scramjet",   ban = true ,  log = true},
}

VCAC_E.AntiNukeBlacklistedPeds = { -- Peds, animals, etc.
	{name = "a_m_m_acult_01", ban = true , log = true},
	{name = "a_m_y_acult_02", ban = true , log = true},
	{name = "a_m_o_acult_01", ban = true , log = true},
	{name = "a_m_y_acult_01", ban = true , log = true},
	{name = "u_m_y_juggernaut_01", ban = true , log = true},
	{name = "u_f_m_drowned_01", ban = true , log = true},
	{name = "s_m_y_swat_01", ban = false , log = false},
	{name = "a_c_sharktiger", ban = false , log = true},
	{name = "a_c_chimp", ban = false , log = true},
	{name = "a_c_humpback", ban = false , log = true},
	{name = "a_c_rhesus", ban = false , log = true},
	{name = "u_m_y_zombie_01", ban = true , log = true},
	{name = "ig_wade", ban = true , log = true},
	{name = "s_m_m_paramedic_01", ban = false , log = false},
	{name = "s_m_y_fireman_01", ban = false , log = false},
}